### PR TITLE
Update to Cake.Recipe 1.1.2 beta 1

### PR DESCRIPTION
**Pull request by pascalberger**
Update build script to beta version of Cake.Recipe. This fixes the issues of sending two notifications on a release.

### CODE REVIEW

**Comment by gep13** [comment]
Looks like I broke something...

Let me get the kids to sleep and then I will take a look.

**Comment by gep13** [comment]
@pascalberger ok, looks like things are working now 😄 

I re-triggered the build on AppVeyor, but you would need to do the same on Azure Pipelines as well.

**Comment by pascalberger** [comment]
@gep13 Package no longer seems to exist on MyGet

**Comment by gep13** [comment]
@pascalberger apologies, I forgot to pin it, and the retention policies deleted it.  Should be there now.

**Pull request merged**
