### PR TITLE
(GH-89) Embed icon in NuGet package

### LINKED ISSUE #89: Embed icon in NuGet package
Use embedded icon for NuGet package

### PR DESCRIPTION
**Pull request by pascalberger**
Uses embedded icon for NuGet package

Fixes #89

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger might be worth running `nuget update -self` rather than attempting to install from Chocolatey.  I have seen issues like this where the already installed version of NuGet is "higher" in the path variable, so it isn't used, even though installed :-(

**Comment by pascalberger** [comment]
> 
> 
> @pascalberger might be worth running `nuget update -self` rather than attempting to install from Chocolatey. I have seen issues like this where the already installed version of NuGet is "higher" in the path variable, so it isn't used, even though installed :-(

Their official suggestion from [here](https://www.appveyor.com/docs/nuget/#download-latest-nuget-command-line) is `appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`, but also doesn't work 🤷‍♂ So `nuget update -self` seems to be the only solution.

**Comment by gep13** [comment]
Chocolatey is still an option, you would just need to mess around with the path variable to remove the other entry for where nuget.exe is hiding 😄

**Comment by pascalberger** [comment]
> Chocolatey is still an option, you would just need to mess around with the path variable to remove the other entry for where nuget.exe is hiding 😄

It's not THAT important after all :)

**Pull request merged**
