### PR TITLE
Fixes #247. 'Environment' does not contain a definition for 'NewLine'

### LINKED ISSUE #247: 'Environment' does not contain a definition for 'NewLine'
when preparing pull request for Cake.Recipe I encountered an error
image

I believe that prefixing given line with System.  will solve problem

### PR DESCRIPTION
**Pull request by AdaskoTheBeAsT**
Fixes #247. 'Environment' does not contain a definition for 'NewLine'

### CODE REVIEW

**Comment by AdaskoTheBeAsT** [comment]
Uff finally ;)

**Review by pascalberger — APPROVED** [review]
LGTM

I removed the updates to the build pipeline, since the build should currently work. The update to the Frosting recipe should also not be required, since this compiles fine and will be consumed as a binary.

**Comment by pascalberger** [comment]
@AdaskoTheBeAsT your changes have been merged, thanks for your contribution 👍

**Comment by AdaskoTheBeAsT** [comment]
Happy to help :)

**Pull request merged**
