### PR TITLE
Add cake-version.yml file to Cake.Issues.Recipe

### LINKED ISSUE #298: Add metadata to package with supported Cake versions and TFMs
We should add metadata for Addin Discoverer to package with supported Cake versions and TFMs.

File should be called `cake-version.yml` in root folder look like this:

```
TargetCakeVersion: 2.0.0
TargetFrameworks:
- netcoreapp3.1
- net5.0
- net6.0
```

### PR DESCRIPTION
**Pull request by pascalberger**
Add version.yml file to Cake.Issues.Recipe

Generated file `cake-version.yml` in root folder will look like this:

```
TargetCakeVersion: 2.0.0
TargetFrameworks:
- netcoreapp3.1
- net5.0
- net6.0
```

Fixes #298

### CODE REVIEW

**Comment by pascalberger** [comment]
@Jericho @gep13 We had recently a discussion how to find out which Cake version a recipe supports. My suggestion would be to establish best-practices for recipes targeting Cake scripting to add a `cake-version.yml` file in the root folder of the nupkg, which contains two properties `TargetCakeVersion` and `TargetFrameworks`. 

Opinions?

**Comment by Jericho** [comment]
What about custom values in the package nuspec? Would that be even lower friction for recipe authors and therefore increase the likelihood they will provide this info?

**Comment by pascalberger** [comment]
> What about custom values in the package nuspec? Would that be even lower friction for recipe authors and therefore increase the likelihood they will provide this info?

Thought about this too, but this would result in invalid XML files for the defined schema, which can result in issues with tools relying on this.

**Comment by Jericho** [comment]
In that case, a custom yaml file is perfect.

**Comment by gep13** [comment]
@pascalberger this seems like a sensible idea to me!

**Review by Jericho — APPROVED** [review]
This will be perfect for my purpose of identifying which version of Cake a recipe is targeting.

**Pull request merged**
