### PR TITLE
Update build script to Cake.Recipe 2.0 alpha

### PR DESCRIPTION
**Pull request by pascalberger**
Update build script to latest alpha version of Cake.Recipe.

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger just to be clear... the fix for sending duplicate notifications isn't currently in the 2.0.0 alpha release.  It is only on the hotfix branch, that hasn't been merged yet.  Was hoping that you would be able to test that before merging into develop branch.

**Comment by pascalberger** [comment]
@gep13 Sure, is there a build somewhere available (MyGet) which I can use?

**Comment by gep13** [comment]
@pascalberger there is an artifact here: https://ci.appveyor.com/project/cakecontrib/cake-recipe/builds/33964005/artifacts which I can push up to MyGet in a minute...

**Comment by gep13** [comment]
@pascalberger package is available here... https://www.myget.org/feed/cake-contrib/package/nuget/Cake.Recipe/1.1.2-beta0001

**Comment by gep13** [comment]
Almost all of the changes that you have made so far in this PR won't be needed in the 1.1.2 beta package.  That is why I wanted to release it as a hotfix, so that these changes won't be needed.

**Comment by gep13** [comment]
It would be great if you could test out the 1.1.2 package and confirm it is working as expected, then I could get it merged into develop branch, ready for the 2.0.0 release.

**Pull request merged**
